import { Camera, Clock, Info, Send, Sparkles, User, X } from 'lucide-react'
import { format } from 'date-fns'
import { RailOverlay } from '../../ui/RailOverlay'
import SectionTitle from '../../ui/SectionTitle'
import { colors, fonts, cardStyle, mutedStyle, radii, titleStyle } from '../../../../lib/design-tokens'
import type { ProgressBodyAnalysis, ProgressPresentationContext } from './progress-tab-types'

export function ProgressBodyAnalysisSection({ analysis, loading, stepLabel, uploadOpen, photos, uploadRef, onChooseAngle, onUpload, onAnalyze, onCloseUpload, onOpenUpload, onContactCoach, ...context }: {
  readonly analysis: ProgressBodyAnalysis | null; readonly loading: boolean; readonly stepLabel: string; readonly uploadOpen: boolean; readonly photos: Readonly<{ front?: string; back?: string; side?: string }>; readonly uploadRef: React.RefObject<HTMLInputElement | null>; readonly onChooseAngle: (angle: 'front' | 'back' | 'side') => void; readonly onUpload: (event: React.ChangeEvent<HTMLInputElement>) => void; readonly onAnalyze: () => void; readonly onCloseUpload: () => void; readonly onOpenUpload: () => void; readonly onContactCoach: () => void
} & ProgressPresentationContext) {
  const { t, dateLocale } = context
  const ready = Boolean(photos.front && photos.back && photos.side)
  return <div style={{ scrollMarginTop: 20 }}>
    <SectionTitle noPadding title={t('tab.aiSection')} trailingNode={<span style={{ fontSize: 9, fontFamily: fonts.headline, fontWeight: 700, color: colors.gold, background: `${colors.goldContainer}1a`, border: `1px solid ${colors.goldRule}`, borderRadius: 999, padding: '2px 8px', display: 'flex', alignItems: 'center', gap: 4 }}><Sparkles size={8} /> BETA</span>} />
    <div style={{ ...cardStyle, padding: 16, marginBottom: 12 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 14 }}><div style={{ width: 36, height: 36, borderRadius: 10, background: `${colors.gold}1a`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><User size={18} color={colors.gold} /></div><div><div style={{ fontFamily: fonts.headline, fontSize: 13, fontWeight: 700, color: colors.text }}>{t('tab.aiAnalysis')}</div><div style={{ ...mutedStyle, fontSize: 10 }}>{t('tab.aiAnalysisDesc')}</div></div></div>
      <div style={{ background: `${colors.goldContainer}0a`, border: `0.5px solid ${colors.goldContainer}1a`, borderRadius: 12, padding: 12, marginBottom: 16, display: 'flex', gap: 10 }}><Info size={14} color={colors.gold} /><span style={{ fontSize: 10, color: 'rgba(255,255,255,0.35)', lineHeight: 1.5 }}>Cette analyse est une estimation par intelligence artificielle. Elle peut contenir des erreurs. Rien ne remplace l&apos;avis d&apos;un professionnel qualifié.</span></div>
      {loading && <div style={{ textAlign: 'center', padding: '32px 0' }}><div style={{ width: 24, height: 24, border: `2px solid ${colors.gold}`, borderTopColor: 'transparent', borderRadius: '50%', animation: 'spin 0.7s linear infinite', margin: '0 auto 12px' }} /><div style={{ fontFamily: fonts.headline, fontSize: 12, color: colors.gold }}>{stepLabel}</div></div>}
      {!loading && analysis && <>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 16 }}>{[['MASSE GRASSE', `~${analysis.body_fat_estimate}%`], ['MASSE MAIGRE', `~${Math.round(analysis.lean_mass_estimate ?? 0)} KG`]].map(([label, value]) => <div key={label} style={{ background: colors.goldDim, borderRadius: 12, padding: 14 }}><div style={{ fontFamily: fonts.headline, fontSize: 8, color: colors.textMuted }}>{label}</div><div style={{ fontFamily: fonts.headline, fontSize: 22, fontWeight: 800, color: colors.gold }}>{value}</div><div style={{ ...mutedStyle, fontSize: 9 }}>{t('tab.aiEstimate')}</div></div>)}</div>
        {[['POINTS FORTS', analysis.strengths, colors.success], ["AXES D'AMÉLIORATION", analysis.improvements, colors.gold]].map(([label, values, color]) => Array.isArray(values) && values.length ? <div key={String(label)} style={{ marginBottom: 14 }}><div style={{ fontFamily: fonts.headline, fontSize: 9, color: 'rgba(255,255,255,0.4)', marginBottom: 8 }}>{String(label)}</div>{values.map((value, index) => <div key={index} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 6, height: 6, borderRadius: '50%', background: String(color) }} /><span style={{ fontSize: 11, color: 'rgba(255,255,255,0.6)' }}>{value}</span></div>)}</div> : null)}
        {analysis.symmetry_score != null && <div style={{ marginBottom: 14 }}><div style={{ fontFamily: fonts.headline, fontSize: 9, color: 'rgba(255,255,255,0.4)', marginBottom: 8 }}>SYMÉTRIE CORPORELLE</div><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><div style={{ flex: 1, height: 6, background: `${colors.gold}1a`, borderRadius: 999 }}><div style={{ width: `${analysis.symmetry_score}%`, height: '100%', background: colors.gold, borderRadius: 999 }} /></div><span style={{ color: colors.gold }}>{analysis.symmetry_score}%</span></div></div>}
        <div style={{ background: `${colors.gold}0a`, borderRadius: 10, padding: 10, display: 'flex', gap: 8 }}><Clock size={12} /><span style={{ fontSize: 9, color: 'rgba(255,255,255,0.25)' }}>Dernière analyse : {analysis.created_at ? format(new Date(analysis.created_at), 'd MMM yyyy', { locale: dateLocale }) : '—'} — Basée sur {analysis.photos_used || 3} photos</span></div>
      </>}
      {!loading && !analysis && <div style={{ textAlign: 'center', padding: '20px 0' }}><User size={28} color={colors.textDim} /><p style={{ ...mutedStyle, fontSize: 12 }}>{t('photos.noAnalysis')}</p><p style={{ fontSize: 10, color: 'rgba(255,255,255,0.25)' }}>{t('tab.upload3Photos')}</p></div>}
    </div>
    {uploadOpen && <RailOverlay><div onClick={onCloseUpload} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', zIndex: 100, display: 'flex', alignItems: 'center', padding: 20 }}><div onClick={event => event.stopPropagation()} style={{ background: colors.background, border: `1px solid ${colors.goldBorder}`, borderRadius: 20, padding: 24, width: '100%' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={titleStyle}>{t('photos.analysisPhotos')}</span><button onClick={onCloseUpload}><X size={14} /></button></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 8, margin: '16px 0' }}>{(['front', 'back', 'side'] as const).map(angle => <div key={angle} onClick={() => { onChooseAngle(angle); uploadRef.current?.click() }} style={{ aspectRatio: '3/4', border: `2px dashed ${colors.goldBorder}`, borderRadius: radii.button, overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>{photos[angle] ? <img src={photos[angle]} alt={angle} style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <Camera size={16} />}</div>)}</div><input ref={uploadRef} type="file" accept="image/*" hidden onChange={onUpload} /><button onClick={onAnalyze} disabled={!ready || loading} style={{ width: '100%', padding: 14, background: ready ? colors.gold : colors.surfaceHigh }}>{loading ? t('tab.analyzing') : t('tab.launchAi')}</button><p style={{ fontSize: 9, textAlign: 'center' }}>{t('tab.aiDisclaimer')}</p></div></div></RailOverlay>}
    <div style={{ display: 'flex', gap: 10, marginBottom: 24 }}><button onClick={onOpenUpload} style={{ ...cardStyle, flex: 1, padding: 14 }}><Camera size={14} /> {t('tab.newAnalysis')}</button><button onClick={onContactCoach} style={{ ...cardStyle, flex: 1, padding: 14 }}><Send size={14} /> {t('tab.seePro')}</button></div>
  </div>
}
