import { X } from 'lucide-react'
import { RailOverlay } from '../../ui/RailOverlay'
import { colors, fonts, bodyStyle, mutedStyle, radii, subtitleStyle, titleStyle } from '../../../../lib/design-tokens'
import type { ProgressTranslate } from './progress-tab-types'

const FIELDS = [{ key: 'waist', label: 'waist' }, { key: 'hips', label: 'hips' }, { key: 'chest', label: 'chest' }, { key: 'arms', label: 'arms' }, { key: 'thighs', label: 'thighs' }] as const

export function ProgressEntryOverlays(props: {
  readonly showWeight: boolean; readonly weight: string; readonly weightDate: string; readonly previousWeight?: number; readonly savingWeight: boolean; readonly onWeightChange: (value: string) => void; readonly onWeightDateChange: (value: string) => void; readonly onCloseWeight: () => void; readonly onSaveWeight: () => void
  readonly showMeasure: boolean; readonly measureForm: Readonly<Record<string, string>>; readonly measureDate: string; readonly savingMeasure: boolean; readonly onMeasureChange: (key: string, value: string) => void; readonly onMeasureDateChange: (value: string) => void; readonly onCloseMeasure: () => void; readonly onSaveMeasure: () => void; readonly t: ProgressTranslate
}) {
  const hasMeasure = Object.values(props.measureForm).some(Boolean)
  return <>
    {props.showWeight && <RailOverlay><div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', zIndex: 1000, display: 'flex', alignItems: 'flex-end' }}><div style={{ background: colors.surface, padding: '28px 20px 48px', width: '100%' }}><Header title="ENREGISTRER MON POIDS" onClose={props.onCloseWeight} /><input type="number" inputMode="decimal" step="0.1" min="0" value={props.weight} onChange={event => props.onWeightChange(event.target.value)} placeholder="0.0" autoFocus style={{ width: '100%', background: colors.background, border: `2px solid ${props.weight ? colors.gold : colors.goldBorder}`, borderRadius: radii.card, padding: 22, color: colors.text, fontSize: '3.2rem', textAlign: 'center' }} />{props.previousWeight !== undefined && <p style={{ textAlign: 'center', ...bodyStyle }}>{props.t('tab.previous', { weight: props.previousWeight })}</p>}<DateField value={props.weightDate} onChange={props.onWeightDateChange} label={props.t('tab.date')} /><button onClick={props.onSaveWeight} disabled={!props.weight || props.savingWeight} style={{ width: '100%', padding: 17, background: props.weight ? colors.gold : colors.surfaceHigh }}>{props.savingWeight ? 'Enregistrement...' : 'Sauvegarder'}</button></div></div></RailOverlay>}
    {props.showMeasure && <RailOverlay><div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', zIndex: 1000, overflowY: 'auto' }}><div style={{ background: colors.surface, padding: '28px 20px 48px', marginTop: 60 }}><Header title={props.t('tab.myMeasurements')} onClose={props.onCloseMeasure} /><div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>{FIELDS.map(field => <div key={field.key} style={{ display: 'flex', alignItems: 'center', background: colors.background, padding: '0 16px' }}><span style={{ ...bodyStyle, flex: 1 }}>{props.t(`tab.measureLabels.${field.label}`)}</span><input type="number" value={props.measureForm[field.key]} onChange={event => props.onMeasureChange(field.key, event.target.value)} style={{ background: 'transparent', color: colors.text, width: 72, border: 'none', padding: 14 }} /><span style={{ ...mutedStyle }}>cm</span></div>)}</div><DateField value={props.measureDate} onChange={props.onMeasureDateChange} label={props.t('tab.date')} /><button onClick={props.onSaveMeasure} disabled={!hasMeasure || props.savingMeasure} style={{ width: '100%', padding: 17, background: hasMeasure ? colors.gold : colors.surfaceHigh }}>{props.savingMeasure ? 'Enregistrement...' : 'Sauvegarder'}</button></div></div></RailOverlay>}
  </>
}

function Header({ title, onClose }: { readonly title: string; readonly onClose: () => void }) { return <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 24 }}><h3 style={{ ...titleStyle, fontSize: 18 }}>{title}</h3><button onClick={onClose}><X size={16} /></button></div> }
function DateField({ value, onChange, label }: { readonly value: string; readonly onChange: (value: string) => void; readonly label: string }) { return <div style={{ margin: '20px 0' }}><label style={subtitleStyle}>{label}</label><input type="date" value={value} onChange={event => onChange(event.target.value)} style={{ width: '100%', background: colors.background, border: `1px solid ${colors.goldBorder}`, borderRadius: radii.card, padding: 14, color: colors.text, fontFamily: fonts.body }} /></div> }
