import { writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import path from 'node:path'

import sharp from 'sharp'

import type { RecoveryMaskView } from '../lib/home/recovery-mask-assets'

const {
  RECOVERY_MASK_ASSETS,
  RECOVERY_MASK_HEIGHT,
  RECOVERY_MASK_WIDTH,
} = await import(new URL('../lib/home/recovery-mask-assets.ts', import.meta.url).href) as typeof import('../lib/home/recovery-mask-assets')

const ROOT = path.resolve(import.meta.dirname, '..')
const OUTPUT = path.join(ROOT, 'lib/home/recovery-hit-map.generated.ts')
const PIXEL_COUNT = RECOVERY_MASK_WIDTH * RECOVERY_MASK_HEIGHT

export type RecoveryHitMapRows = Readonly<Record<RecoveryMaskView, readonly (readonly number[])[]>>

function publicAssetPath(assetPath: string): string {
  if (!assetPath.startsWith('/images/')) throw new Error(`Unexpected public asset path: ${assetPath}`)
  return path.join(ROOT, 'public', assetPath)
}

export async function buildRecoveryHitMapRows(): Promise<RecoveryHitMapRows> {
  const maps = {} as Record<RecoveryMaskView, number[][]>

  for (const view of ['front', 'back'] as const) {
    const pixels = new Uint8Array(PIXEL_COUNT)
    for (const asset of RECOVERY_MASK_ASSETS.filter(candidate => candidate.view === view)) {
      const { data, info } = await sharp(publicAssetPath(asset.maskPath))
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true })
      if (info.width !== RECOVERY_MASK_WIDTH || info.height !== RECOVERY_MASK_HEIGHT || info.channels !== 4) {
        throw new Error(`Invalid mask geometry: ${asset.maskPath}`)
      }
      for (let pixel = 0; pixel < PIXEL_COUNT; pixel += 1) {
        if (data[pixel * 4 + 3] === 0) continue
        if (pixels[pixel] !== 0) throw new Error(`Overlapping ${view} masks at pixel ${pixel}`)
        pixels[pixel] = asset.atlasId
      }
    }

    maps[view] = Array.from({ length: RECOVERY_MASK_HEIGHT }, (_, y) => {
      const row: number[] = []
      for (let x = 0; x < RECOVERY_MASK_WIDTH; x += 1) {
        const zoneId = pixels[y * RECOVERY_MASK_WIDTH + x]
        if (zoneId === 0) continue
        const xStart = x
        while (x + 1 < RECOVERY_MASK_WIDTH && pixels[y * RECOVERY_MASK_WIDTH + x + 1] === zoneId) x += 1
        row.push(xStart, x, zoneId)
      }
      return row
    })
  }

  return maps
}

export async function buildRecoveryHitMapSource(): Promise<string> {
  const rows = await buildRecoveryHitMapRows()
  return `// Generated by scripts/generate-recovery-hit-map.ts from the canonical Recovery PNG masks.\n// Do not edit manually. Each row stores [xStart, xEnd, zoneId] segments.\n\nexport const RECOVERY_HIT_MAP_ROWS = ${JSON.stringify(rows)} as const\n`
}

export async function generateRecoveryHitMap(): Promise<void> {
  await writeFile(OUTPUT, await buildRecoveryHitMapSource())
}

const isCli = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
if (isCli) {
  await generateRecoveryHitMap()
  console.log('Generated static Recovery hit map: front, back')
}
