-- Sprint 5 — Add missing parent exercises to catalog
-- These exercises are commonly generated by the AI program builder
-- but were missing from exercises_db, causing video/gif matching failures.
-- video_url and gif_url are NULL for now — to be enriched with media later.

INSERT INTO public.exercises_db (name, muscle_group, equipment)
VALUES
  ('Dips', 'Triceps', 'Barres parallèles'),
  ('Hip Thrust', 'Fessiers', 'Barre'),
  ('Tractions', 'Dos', 'Barre de traction'),
  ('Développé Couché', 'Pectoraux', 'Barre'),
  ('Développé Militaire', 'Épaules', 'Barre'),
  ('Squat', 'Quadriceps', 'Barre'),
  ('Squat Haltères', 'Quadriceps', 'Haltères'),
  ('Mollets Debout', 'Mollets', 'Machine'),
  ('Planche', 'Abdominaux', 'Poids du corps'),
  ('Rowing Barre', 'Dos', 'Barre'),
  ('Rowing Haltère', 'Dos', 'Haltère'),
  ('Leg Curl Couché', 'Ischio-jambiers', 'Machine'),
  ('Face Pulls', 'Épaules', 'Poulie'),
  ('Good Morning', 'Ischio-jambiers', 'Barre'),
  ('Fentes', 'Quadriceps', 'Poids du corps'),
  ('Tirage Vertical', 'Dos', 'Poulie'),
  ('Élévations Latérales', 'Épaules', 'Haltères'),
  ('Élévations Frontales', 'Épaules', 'Haltères'),
  ('Curl Barre EZ', 'Biceps', 'Barre EZ'),
  ('Extension Triceps Poulie', 'Triceps', 'Poulie'),
  ('Triceps Poulie Corde', 'Triceps', 'Poulie'),
  ('Fente Bulgare', 'Quadriceps', 'Haltères'),
  ('Kickbacks Câble', 'Fessiers', 'Poulie'),
  ('Abduction Machine', 'Fessiers', 'Machine'),
  ('Pont Fessier', 'Fessiers', 'Poids du corps')
ON CONFLICT (name) DO NOTHING;
