// @vitest-environment jsdom
import * as React from 'react'
import { render, screen, fireEvent, cleanup, waitFor, act } from '@testing-library/react'
import { beforeEach, afterEach, describe, it, expect, vi } from 'vitest'
import messages from '@/messages/fr.json'
const reorderHarness = vi.hoisted(() => ({ values: [] as any[], change: (_: any[]) => {} }))
vi.mock('framer-motion', () => ({ Reorder: {
  Group: (props: any) => { reorderHarness.values = props.values; reorderHarness.change = props.onReorder; return React.createElement('div', null, props.children) },
  Item: (props: any) => React.createElement('div', null, props.children),
} }))
const followupEnabled = vi.hoisted(() => ({ value: false }))
const catalogRows = vi.hoisted(() => ({ value: [] as Array<Record<string, unknown>> }))
const warningTick = vi.hoisted(() => vi.fn())
const nativeRest = vi.hoisted(() => ({ schedule: vi.fn(), cancel: vi.fn(), scheduleSound: vi.fn(() => []), cancelSound: vi.fn() }))
vi.mock('next-intl',()=>({useLocale:()=> 'fr',useTranslations:(namespace:string)=> (key:string,values:Record<string,unknown>={})=>{
  const obj=namespace.split('.').reduce((o:any,k)=>o?.[k],messages)
  return String(obj?.[key]??key).replace(/\{(\w+)\}/g,(_,k)=>String(values[k]??k))
}}))
vi.mock('@supabase/ssr',()=>({createBrowserClient:()=>({
  auth:{getUser:async()=>({data:{user:null}})},
  from:(table:string)=>{
    const query:any={}
    query.select=()=>query
    query.ilike=()=>query
    query.eq=()=>query
    query.abortSignal=()=>query
    query.or=()=>query
    query.range=()=>query
    query.limit=()=>query
    query.order=()=>query
    query.then=(resolve:any)=>Promise.resolve({data:table==='exercises_catalog'?catalogRows.value:[]}).then(resolve)
    return query
  },
})}))
vi.mock('@/app/hooks/useTrainingFollowup',()=>({useTrainingFollowup:()=>({preferences:{enabled:followupEnabled.value,advanced_techniques:followupEnabled.value}})}))
vi.mock('@/lib/timer-audio',()=>({initAudio:()=>{},finishRestPeriodSounds:()=>{},playWarningTick:warningTick,vibrateDevice:()=>{},scheduleRestPeriodSounds:nativeRest.scheduleSound,cancelScheduledSounds:nativeRest.cancelSound,scheduleNativeRestNotification:nativeRest.schedule,cancelNativeRestNotification:nativeRest.cancel}))
import WorkoutSession from '@/app/components/WorkoutSession'
import { createActiveWorkoutDraft, type ActiveWorkoutDraft } from '@/lib/training/active-workout-draft'
beforeEach(()=>{followupEnabled.value=false;catalogRows.value=[];warningTick.mockClear();Object.values(nativeRest).forEach(mock=>mock.mockClear());vi.stubGlobal('React',React);localStorage.clear();vi.spyOn(HTMLMediaElement.prototype,'play').mockResolvedValue();vi.spyOn(HTMLMediaElement.prototype,'pause').mockImplementation(()=>{})})
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals()})
const start=(exercises:unknown[],existing?:ActiveWorkoutDraft)=>{
  const draft=existing??createActiveWorkoutDraft({userId:'synthetic',programSource:'personal',programId:null,sessionName:'Test',sessionKey:'test',exercises})
  let saved=draft
  const finish=vi.fn().mockResolvedValue({})
  const view=render(React.createElement(WorkoutSession,{draft,onDraftChange:(v:ActiveWorkoutDraft)=>{saved=v},onFinish:finish,onClose:()=>{},onNavigateHome:()=>{},onNavigateProgress:()=>{}}))
  return {...view,saved:()=>saved,finish}
}
const log=(weight:string)=>{
  fireEvent.change(screen.getByLabelText('Charge'),{target:{value:weight}})
  fireEvent.blur(screen.getByLabelText('Charge'))
  fireEvent.change(screen.getByLabelText('Répétitions'),{target:{value:'10'}})
  fireEvent.click(screen.getByRole('button',{name:'Valider la série'}))
}
describe('real WorkoutSession runtime',()=>{
  it('validates a repeated exercise independently after completing the earlier occurrence and reopening',()=>{
    const view=start([{id:'same-catalog-id',name:'Pull-over',sets:1,reps:10},{id:'middle',name:'Rowing',sets:1,reps:10},{id:'same-catalog-id',name:'Pull-over',sets:1,reps:10}])
    log('30');log('25');
    const draft=view.saved();view.unmount()
    // Simulate a persisted draft written before occurrence IDs were repaired.
    draft.exercises[2].id=draft.exercises[0].id
    const next=start([],draft)
    log('20')
    expect(next.saved().exercises.map(e=>e.sets[0].done)).toEqual([true,true,true])
    expect(next.saved().exercises.map(e=>e.sets[0].weight)).toEqual([30,25,20])
    expect(new Set(next.saved().exercises.map(e=>e.id)).size).toBe(3)
  })

  it('opens and closes the exercise options without changing entered sets',()=>{
    const view=start([{name:'Rowing',sets:2,reps:10}])
    const menu=screen.getByRole('button',{name:'Rowing, Options de l’exercice'})
    expect(menu.getAttribute('aria-expanded')).toBe('false')
    fireEvent.click(menu)
    expect(menu.getAttribute('aria-expanded')).toBe('true')
    const panel=document.getElementById(menu.getAttribute('aria-controls')!) as HTMLDetailsElement
    expect(panel.open).toBe(true)
    fireEvent.change(screen.getByLabelText('Charge'),{target:{value:'28'}})
    fireEvent.click(menu)
    expect(panel.open).toBe(false)
    expect(view.saved().exercises[0].sets[0].weightRaw).toBe('28')
  })
  it('explains an out-of-order biset validation and keeps both sets unvalidated',()=>{
    const view=start([{name:'A',sets:1,reps:10,technique:'superset',technique_details:'B'},{name:'B',sets:1,reps:10}])
    fireEvent.click(screen.getByRole('button',{name:'B · Série 1 · Valider la série'}))
    expect(view.saved().currentExerciseIndex).toBe(0)
    expect(view.saved().exercises.every(e=>e.sets.every(s=>!s.done))).toBe(true)
    expect(screen.getByText(messages.trainingTechnique.bisetOrder)).toBeTruthy()
  })

  it('shows every exercise and preserves future-row edits when changing exercise order',()=>{
    const view=start([{name:'Squat',sets:2,reps:10},{name:'Rowing',sets:2,reps:10}])
    expect(screen.getByRole('heading',{name:'Squat Barre'})).toBeTruthy()
    expect(screen.getByRole('heading',{name:'Rowing'})).toBeTruthy()
    fireEvent.change(screen.getByLabelText('Rowing · Série 2 · Charge'),{target:{value:'28'}})
    fireEvent.change(screen.getByLabelText('Rowing · Série 2 · Répétitions'),{target:{value:'12'}})
    expect((screen.getByRole('button',{name:'Rowing · Série 2 · Valider la série'}) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.click(screen.getByRole('button',{name:'Rowing, Options de l’exercice'}))
    log('26')
    expect((screen.getByLabelText('Charge') as HTMLInputElement).value).toBe('28')
    expect((screen.getByLabelText('Répétitions') as HTMLInputElement).value).toBe('12')
    fireEvent.click(screen.getByRole('button',{name:'Valider la série'}))
    expect(view.saved().exercises[1].sets.map(s=>s.weight)).toEqual([26,28])
    expect(view.saved().exercises[0].sets.every(s=>!s.done)).toBe(true)
  })
  it('rejects empty set values and keeps zero load valid',()=>{
    const view=start([{name:'Pompes',sets:1,reps:10}])
    fireEvent.click(screen.getByRole('button',{name:'Valider la série'}))
    expect(view.saved().exercises[0].sets[0].done).toBe(false)
    expect(screen.getByText(/Renseigne une charge valide/)).toBeTruthy()
    log('0')
    expect(view.saved().exercises[0].sets[0].done).toBe(true)
    expect(view.saved().exercises[0].sets[0].weight).toBe(0)
  })
  it('keeps paired exercises adjacent even when another exercise lies between them',()=>{
    start([{name:'A',sets:2,reps:10,technique:'superset',technique_details:'B'},{name:'Solo',sets:1,reps:10},{name:'B',sets:2,reps:10}])
    expect(screen.getAllByRole('heading',{level:2}).filter(e=>e.closest('[data-paired]')).map(e=>e.textContent)).toEqual(['A','B','Solo'])
    expect(screen.getByText('Biset · A1 avec B')).toBeTruthy()
    expect(screen.getByText('Biset · A2 avec A')).toBeTruthy()
  })
  it('logs a timed set from the ledger and preserves it across reload',()=>{
    const view=start([{name:'Gainage',sets:2,duration_seconds:45}])
    fireEvent.change(screen.getByLabelText(messages.training_tab.v2.durationSeconds),{target:{value:'45'}})
    fireEvent.click(screen.getByRole('button',{name:'Valider la série'}))
    const draft=view.saved();view.unmount()
    const next=start([],draft)
    expect(next.saved().exercises[0].sets[0].durationSeconds).toBe(45)
    expect(next.saved().exercises[0].sets[0].done).toBe(true)
    expect(screen.queryByLabelText('Charge')).toBeNull()
  })

  it('adds an exercise after finishing the current one, focuses it and validates without reopening',async()=>{
    catalogRows.value=[{id:'new-exercise',name:'Rowing',muscle_group:'Dos'}]
    const view=start([{name:'Squat',sets:1,reps:10}])
    log('40')
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.ws.addExercise}))
    await screen.findByRole('button',{name:/Rowing/})
    fireEvent.click(screen.getByRole('button',{name:/Rowing/}))
    fireEvent.click(screen.getByRole('button',{name:'builder.next'}))
    fireEvent.click(screen.getByRole('button',{name:'builder.launchSession'}))
    expect(screen.getByRole('heading',{name:'Rowing'})).toBeTruthy()
    expect(view.saved().exercises).toHaveLength(2)
    expect(view.saved().currentExerciseIndex).toBe(1)
    log('25')
    expect(view.saved().exercises[1].sets[0].done).toBe(true)
    expect(view.saved().exercises[0].sets[0].weight).toBe(40)
  })
  it('rejects an oversized set count before constructing the workout',async()=>{
    catalogRows.value=[{id:'new-exercise',name:'Rowing',muscle_group:'Dos'}]
    const view=start([{name:'Squat',sets:1,reps:10}])
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.ws.addExercise}))
    fireEvent.click(await screen.findByRole('button',{name:/Rowing/}))
    fireEvent.click(screen.getByRole('button',{name:'builder.next'}))
    fireEvent.change(screen.getByLabelText('builder.sets'),{target:{value:'1000000'}})
    fireEvent.click(screen.getByRole('button',{name:'builder.launchSession'}))
    expect(screen.getByRole('alert').textContent).toContain('entre 1 et 10 séries')
    expect(view.saved().exercises).toHaveLength(1)
  })
  it('keeps background scroll locked while adding or cancelling and restores it on exit',()=>{
    document.body.style.overflow='auto'
    const view=start([{name:'Squat',sets:1,reps:10}])
    expect(document.body.style.overflow).toBe('hidden')
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.ws.addExercise}))
    expect(document.body.style.overflow).toBe('hidden')
    fireEvent.click(screen.getByRole('button',{name:'Retour'}))
    expect(document.body.style.overflow).toBe('hidden')
    view.unmount();expect(document.body.style.overflow).toBe('auto')
    document.body.style.overflow=''
  })

  it('keeps the same unfinished exercise after reordering past a completed exercise',()=>{
    const view=start([{name:'Squat',sets:1,reps:10},{name:'Rowing',sets:2,reps:10}])
    log('40')
    fireEvent.change(screen.getByLabelText('Charge'),{target:{value:'25'}})
    fireEvent.change(screen.getByLabelText('Répétitions'),{target:{value:'10'}})
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.ws.reorderLink}))
    act(()=>reorderHarness.change([...reorderHarness.values].reverse()))
    fireEvent.click(screen.getByRole('button',{name:'reorder.done'}))
    expect(screen.getByRole('heading',{name:'Rowing'})).toBeTruthy()
    expect((screen.getByRole('button',{name:'Valider la série'}) as HTMLButtonElement).disabled).toBe(false)
    expect(view.saved().currentExerciseIndex).toBe(0)
    fireEvent.click(screen.getByRole('button',{name:'Valider la série'}))
    expect(view.saved().exercises.find(e=>e.name==='Rowing')?.sets[0].done).toBe(true)
  })
  it('explains a completed exercise instead of showing an editable set with disabled validation',()=>{
    const view=start([{name:'Squat',sets:1,reps:10},{name:'Rowing',sets:2,reps:10}])
    log('40')
    fireEvent.click(screen.getByRole('button',{name:/^Squat Barre,/}))
    expect(screen.queryByRole('button',{name:'Valider la série'})).toBeNull()
    expect(screen.getByText('Toutes les séries de cet exercice sont validées.')).toBeTruthy()
    fireEvent.click(screen.getByRole('button',{name:'Reprendre un exercice à terminer'}))
    expect(screen.getByRole('heading',{name:'Rowing'})).toBeTruthy()
    expect(view.saved().exercises[0].sets[0].weight).toBe(40)
  })
  it.each(['dropset','restpause'])('resumes unfinished %s stages after another exercise and reload',technique=>{
    const view=start([{name:'Curl',sets:1,reps:10,technique,technique_details:technique==='dropset'?'1':'2,15'},{name:'Rowing',sets:2,reps:10}])
    log('20')
    fireEvent.click(screen.getByRole('button',{name:/^Rowing,/}))
    log('25')
    const draft=view.saved();view.unmount()
    const resumed=start([],draft)
    fireEvent.click(screen.getByRole('button',{name:/^Curl,/}))
    log(technique==='dropset'?'15':'20')
    expect(resumed.saved().exercises[0].sets[1].done).toBe(true)
    expect(resumed.saved().exercises[1].sets[0].done).toBe(true)
  })

  it('allows skipping an exercise and returning with its entered values intact',()=>{
    const view=start([{name:'Squat',sets:2,reps:10},{name:'Rowing',sets:2,reps:10}])
    fireEvent.change(screen.getByLabelText('Charge'),{target:{value:'40'}})
    fireEvent.change(screen.getByLabelText('Répétitions'),{target:{value:'10'}})
    fireEvent.click(screen.getByRole('button',{name:/^Rowing,/}))
    log('25')
    fireEvent.click(screen.getByRole('button',{name:/^Squat Barre,/}))
    expect((screen.getByLabelText('Charge') as HTMLInputElement).value).toBe('40')
    expect((screen.getByRole('button',{name:'Valider la série'}) as HTMLButtonElement).disabled).toBe(false)
    fireEvent.click(screen.getByRole('button',{name:'Valider la série'}))
    expect(view.saved().exercises[0].sets[0].done).toBe(true)
    expect(view.saved().exercises[1].sets[0].done).toBe(true)
  })

  it('reconciles one native rest deadline on mount and return, then extends and cancels it',()=>{
    start([{name:'Squat',sets:2,reps:10,rest:10}])
    log('20')
    expect(nativeRest.schedule).toHaveBeenCalledTimes(2)
    const originalDeadline = nativeRest.schedule.mock.calls[0][0] as number
    expect(nativeRest.schedule.mock.calls[1][0]).toBe(originalDeadline)
    act(()=>{window.dispatchEvent(new Event('pageshow'))})
    expect(nativeRest.schedule).toHaveBeenCalledTimes(3)
    expect(nativeRest.schedule.mock.calls[2][0]).toBe(originalDeadline)
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.v2.addRestTime}))
    expect(nativeRest.schedule).toHaveBeenCalledTimes(4)
    expect(nativeRest.schedule.mock.calls[3][0]).toBeGreaterThan(originalDeadline)
    expect(nativeRest.cancelSound).toHaveBeenCalledOnce()
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.v2.skipRest}))
    expect(nativeRest.cancel).toHaveBeenCalledOnce()
  })
  it('leaves the native alert intact at the deadline for locked-screen delivery',()=>{
    vi.useFakeTimers()
    start([{name:'Squat',sets:2,reps:10,rest:3}])
    log('20')
    act(()=>{vi.advanceTimersByTime(3200)})
    expect(nativeRest.schedule).toHaveBeenCalledTimes(2)
    expect(nativeRest.cancel).not.toHaveBeenCalled()
  })
  it('plays the five-second warning once after returning from another app',()=>{
    vi.useFakeTimers()
    const visibility = vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('hidden')
    start([{name:'Squat',sets:2,reps:10,rest:10}])
    log('20')
    act(()=>{vi.advanceTimersByTime(5500)})
    expect(warningTick).not.toHaveBeenCalled()
    visibility.mockReturnValue('visible')
    act(()=>{document.dispatchEvent(new Event('visibilitychange'));vi.advanceTimersByTime(200)})
    expect(warningTick).toHaveBeenCalledOnce()
    act(()=>{vi.advanceTimersByTime(1000)})
    expect(warningTick).toHaveBeenCalledOnce()
  })
  it('does not play a five-second warning for a shorter rest',()=>{
    vi.useFakeTimers()
    start([{name:'Squat',sets:2,reps:10,rest:3}])
    log('20')
    act(()=>{vi.advanceTimersByTime(2500)})
    expect(warningTick).not.toHaveBeenCalled()
  })
  it('keeps the native screen awake only while the workout is open',()=>{
    const postMessage=vi.fn()
    vi.stubGlobal('webkit',{messageHandlers:{moovxWorkoutActive:{postMessage}}})
    const view=start([{name:'Squat',sets:1,reps:10}])
    expect(postMessage).toHaveBeenCalledWith(true)
    view.unmount()
    expect(postMessage).toHaveBeenLastCalledWith(false)
  })
  it('executes rest-pause only after the final main set, resumes and saves separate mini-sets',async()=>{
    const view=start([{name:'Curl',sets:3,reps:10,rest:90,technique:'restpause',technique_details:'2,15'}])
    await screen.findByRole('region',{name:'REST-PAUSE — après la dernière série uniquement'})
    expect(screen.queryByText('2,15')).toBeNull()
    expect(view.saved().exercises[0].sets).toHaveLength(5)
    log('25')
    expect(Date.parse(view.saved().restTimerEndAt!)-Date.now()).toBeGreaterThan(88000)
    log('25');log('25')
    expect(screen.getAllByText('Mini-série 1/2').length).toBeGreaterThan(0)
    expect(Date.parse(view.saved().restTimerEndAt!)-Date.now()).toBeGreaterThan(13000)
    expect(Date.parse(view.saved().restTimerEndAt!)-Date.now()).toBeLessThanOrEqual(15000)
    log('20');expect(view.saved().exercises[0].sets[3].done).toBe(false)
    log('25')
    const saved=view.saved();view.unmount()
    const resumed=start([],saved)
    expect(resumed.saved().exercises[0].sets).toHaveLength(5)
    expect(screen.getAllByText('Mini-série 2/2').length).toBeGreaterThan(0)
    log('25')
    expect(resumed.saved().restTimerEndAt).toBeNull()
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.ws.finish}))
    fireEvent.click(screen.getByRole('button',{name:'endModal.save'}))
    await waitFor(()=>expect(resumed.finish).toHaveBeenCalledOnce())
    expect(resumed.finish.mock.calls[0][0].exercises[0].sets.map((s:any)=>s.parentSetNumber)).toEqual([undefined,undefined,undefined,3,4])
  })
  it('renders all seven FST-7 stages immediately and no incompatible controls',async()=>{
    start([{name:'Raise',sets:7,reps:'8-12',rest:45,technique:'fst7'}])
    expect(screen.getByRole('list',{name:'FST-7'}).children).toHaveLength(7)
    expect(screen.getByText('FST-7 7/7')).toBeTruthy()
    expect(screen.getByRole('listitem',{current:'step'})).toBeTruthy()
    expect(screen.queryByRole('button',{name:messages.trainingTechnique.addDrop})).toBeNull()
  })
  it('shows prepared drops, transitions immediately, refuses a non-reduced load and resumes the stage',async()=>{
    const view=start([{name:'Row',sets:1,reps:10,technique:'dropset',technique_details:'2'}])
    await screen.findByText(/2 paliers dégressifs préparés/)
    expect(screen.getByRole('list',{name:'DROP SET'}).children).toHaveLength(3)
    expect(screen.getByText('Palier dégressif 1/2')).toBeTruthy()
    expect(screen.getByText('Palier dégressif 2/2')).toBeTruthy()
    expect(screen.getByRole('button',{name:'+ Ajouter une série principale'})).toBeTruthy()
    log('40')
    expect(screen.getByText(/Maintenant : palier dégressif 1\/2/)).toBeTruthy()
    expect(view.saved().restTimerEndAt).toBeNull()
    log('40');expect(view.saved().exercises[0].sets[1].done).toBe(false)
    log('30');expect(screen.getByText(/Maintenant : palier dégressif 2\/2/)).toBeTruthy()
    const saved=view.saved();view.unmount()
    const resumed=start([],saved)
    expect(screen.getByText(/Maintenant : palier dégressif 2\/2/)).toBeTruthy()
    log('20')
    expect(resumed.saved().exercises[0].sets.map(s=>s.weight)).toEqual([40,30,20])
    expect(resumed.saved().exercises[0].sets.every(s=>s.done)).toBe(true)
    expect(resumed.saved().restTimerEndAt).toBeNull()
    fireEvent.click(screen.getByRole('button',{name:messages.training_tab.ws.finish}))
    fireEvent.click(screen.getByRole('button',{name:'endModal.save'}))
    await waitFor(()=>expect(resumed.finish).toHaveBeenCalledOnce())
    const payload=resumed.finish.mock.calls[0][0]
    expect(payload.exercises[0].technique).toBe('dropset')
    expect(payload.exercises[0].sets.map((s:any)=>s.parentSetNumber)).toEqual([undefined,1,2])
    expect(payload.totalVolume).toBe(900)
  })
  it('shows both biset members and alternates the actual focus with rest after B',async()=>{
    const view=start([{name:'A',sets:2,reps:10,technique:'superset',technique_details:'B'},{name:'B',sets:2,reps:10,rest:60}])
    await screen.findByText(/Alterner A \(A\) puis B \(B\)/)
    expect(screen.getByRole('list',{name:'A · A'}).children).toHaveLength(2)
    expect(screen.getByRole('list',{name:'B · B'}).children).toHaveLength(2)
    log('20')
    expect(view.saved().currentExerciseIndex).toBe(1)
    expect(view.saved().restTimerEndAt).toBeNull()
    log('15')
    expect(view.saved().currentExerciseIndex).toBe(0)
    expect(Date.parse(view.saved().restTimerEndAt!)-Date.now()).toBeGreaterThan(58000)
    expect(view.saved().exercises[1].technique).toBe('superset')
  })
  it('starts a biset during the workout and persists its A/B flow',async()=>{
    followupEnabled.value=true
    const view=start([{name:'Raise',sets:1,reps:10},{name:'Press',sets:1,reps:10}])
    fireEvent.click(screen.getByText('Modifier la technique'))
    fireEvent.change(screen.getByLabelText('Créer un biset pour cette séance'),{target:{value:'1'}})
    expect(screen.getByText('A · Raise')).toBeTruthy()
    expect(screen.getByText('B · Press')).toBeTruthy()
    const saved=view.saved();view.unmount()
    const resumed=start([],saved)
    expect(resumed.saved().exercises.map(exercise=>exercise.technique)).toEqual(['superset','superset'])
    log('20')
    expect(resumed.saved().currentExerciseIndex).toBe(1)
    expect(resumed.saved().restTimerEndAt).toBeNull()
  })
  it('explains why a single exercise cannot form a biset yet',()=>{
    followupEnabled.value=true
    start([{name:'Raise',sets:3,reps:10}])
    fireEvent.click(screen.getByText('Modifier la technique'))
    expect((screen.getByLabelText(/Créer un biset pour cette séance/) as HTMLSelectElement).disabled).toBe(true)
    expect(screen.getByText(/Aucun partenaire compatible dans cette séance/)).toBeTruthy()
    expect(screen.getByRole('button',{name:'+ Ajouter un exercice au biset'})).toBeTruthy()
  })
  it('offers a manual biset when Athena followup is disabled',()=>{
    const view=start([{name:'Raise',sets:3,reps:10}])
    fireEvent.click(screen.getByText('Modifier la technique'))
    expect(screen.getByRole('button',{name:'+ Ajouter un exercice au biset'})).toBeTruthy()
    expect(screen.queryByRole('button',{name:'Configurer cet exercice en 7 séries FST-7'})).toBeNull()
    expect(screen.queryByRole('button',{name:'Ajouter un palier de drop set final'})).toBeNull()
    expect(view.saved().exercises).toHaveLength(1)
  })
  it('completes the one-exercise to catalogue partner to biset journey',async()=>{
    catalogRows.value=[
      {id:'source',name:'Développé couché barre',muscle_group:'Pectoraux'},
      {id:'partner',name:'Écarté poulie',muscle_group:'Pectoraux'},
    ]
    const view=start([{name:'Développé couché barre',sets:3,reps:10}])
    fireEvent.click(screen.getByText('Modifier la technique'))
    fireEvent.click(screen.getByRole('button',{name:'+ Ajouter un exercice au biset'}))
    expect(await screen.findByText(/Avec Développé Couché Barre · 3 séries chacun/)).toBeTruthy()
    expect((await screen.findByRole('button',{name:/Développé couché barre/i}) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.click(screen.getByRole('button',{name:/Écarté poulie/i}))
    fireEvent.click(screen.getByRole('button',{name:'builder.next'}))
    expect((screen.getByDisplayValue('3') as HTMLInputElement).disabled).toBe(true)
    fireEvent.click(screen.getAllByRole('button',{name:'Créer le biset'})[0])
    expect(view.saved().exercises.map(exercise=>exercise.technique)).toEqual(['superset','superset'])
    expect(screen.getByText(/A · Développé Couché Barre/)).toBeTruthy()
    expect(screen.getByText(/B · Écarté/i)).toBeTruthy()
    expect(view.saved().exercises).toHaveLength(2)
    expect(view.saved().exercises.map(exercise=>exercise.targetSets)).toEqual([3,3])
    const saved=view.saved();view.unmount()
    const resumed=start([],saved)
    expect(screen.getByText(/B · Écarté/i)).toBeTruthy()
    log('60')
    expect(resumed.saved().currentExerciseIndex).toBe(1)
  })
  it('does not change the workout when the partner picker is cancelled',()=>{
    followupEnabled.value=true
    const view=start([{name:'Raise',sets:3,reps:10}])
    fireEvent.click(screen.getByText('Modifier la technique'))
    fireEvent.click(screen.getByRole('button',{name:'+ Ajouter un exercice au biset'}))
    fireEvent.click(screen.getByRole('button',{name:'Retour'}))
    expect(view.saved().exercises).toHaveLength(1)
    expect(view.saved().exercises[0].technique).toBeUndefined()
  })
  it('adds an extra set mid-session and keeps it after reopening the draft',async()=>{
    const view=start([{name:'Raise',sets:1,reps:10}])
    log('10')
    fireEvent.click(screen.getByRole('button',{name:'+ Ajouter une série'}))
    expect(view.saved().exercises[0].sets).toHaveLength(2)
    expect(view.saved().currentSetIndex).toBe(1)
    const saved=view.saved();view.unmount()
    const resumed=start([],saved)
    expect(screen.getAllByText(/Série 2 sur 2/).length).toBeGreaterThan(0)
    log('12')
    expect(resumed.saved().exercises[0].sets.every(set=>set.done)).toBe(true)
  })
  it('adds an extra round to both members of a running biset',async()=>{
    const view=start([{name:'A',sets:1,reps:10,technique:'superset',technique_details:'B'},{name:'B',sets:1,reps:10}])
    fireEvent.click(screen.getByRole('button',{name:'+ Ajouter une série aux deux exercices'}))
    expect(view.saved().exercises.map(exercise=>exercise.sets.length)).toEqual([2,2])
    expect(view.saved().exercises.map(exercise=>exercise.targetSets)).toEqual([2,2])
  })
  it('shows the selected partner explicitly and repairs an orphaned biset without changing the program',async()=>{
    const view=start([{name:'Élévations frontales poulie',sets:1,reps:10,technique:'superset',technique_details:'Oiseau / Reverse Fly'},{name:'Reverse pec deck',sets:1,reps:10}])
    expect(screen.getByText(/Oiseau \/ Reverse Fly.*n’est pas disponible/)).toBeTruthy()
    expect((screen.getByRole('button',{name:'Valider la série'}) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.change(screen.getByLabelText('Choisir un exercice présent'),{target:{value:'1'}})
    expect(screen.getByText('B · Reverse pec deck')).toBeTruthy()
    log('10')
    expect(view.saved().currentExerciseIndex).toBe(1)
    expect(view.saved().exercises[1].technique).toBe('superset')
  })
  it('lets a blocked historical biset continue only after an explicit solo choice',async()=>{
    const view=start([{name:'Raise',sets:1,reps:10,technique:'superset',technique_details:'Missing'}])
    fireEvent.click(screen.getByRole('button',{name:'Continuer cet exercice seul'}))
    expect(screen.queryByRole('alert')).toBeNull()
    log('10')
    expect(view.saved().exercises[0].sets[0].done).toBe(true)
    expect(view.saved().exercises[0].technique).toBeUndefined()
  })
  it('blocks a missing biset partner instead of silently logging ordinary sets',async()=>{
    start([{name:'Raise',sets:3,reps:10,technique:'superset',technique_details:'Missing'}])
    await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('Biset incomplet'))
    expect((screen.getByRole('button',{name:'Valider la série'}) as HTMLButtonElement).disabled).toBe(true)
  })
})
